// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'user_module';

  static const String assets_animations_flower_animation_json = 'assets/animations/flower_animation.json';
  static const String user_module$assets_animations_flower_animation_json = 'packages/user_module/assets/animations/flower_animation.json';

  static const String assets_animations_login_loading_json = 'assets/animations/login_loading.json';
  static const String user_module$assets_animations_login_loading_json = 'packages/user_module/assets/animations/login_loading.json';

  static const String assets_images_login_background_png = 'assets/images/login_background.png';
  static const String user_module$assets_images_login_background_png = 'packages/user_module/assets/images/login_background.png';

  static const String assets_images_logo_png = 'assets/images/logo.png';
  static const String user_module$assets_images_logo_png = 'packages/user_module/assets/images/logo.png';
}
